function gui_help(which_help)
%
% function gui_help()
% Used by GUI_CALLBACK
% 
switch which_help
    case 'gui_cb_about'
        helptitle = 'About EEG_TF';
        helptext =[ ...
            'EEG_TF for Matlab 9                                                       '
            'Version 0.1, May 2021                                                     '
            'Copyright (c) Alina Beliakova.                                            '
            '                                                                          '
            'For more information please visit:                                        '
            'https://github.com/AlinaBeliakova/EEG_TF                                  '];
            
    case 'gui_cb_help'
        helptitle = 'EEG_TF GUI';
        helptext = [...
            'The guide to the EEG_TF App                                                '
            'Read the detailed guide EEG_TF.PDF for more info                           '
            '                                                                           '
            'The EEG_TF is a MATLAB toolbox designed to visualize time-frequency        '
            'maps (spectrograms) of the EEG (or any other 3D or 2D) signals.            '
            'The app uses MATLAB and EEGLAB to operate through the GUI.                 '
            '                                                                           '
            'Requirements:                                                              '
            '- MATLAB R2018a and newer                                                  '
            '- MATLAB Signal processing toolbox (for Short-Time Fourier Transform,      '
            'wavelets do not require any toolbox)                                       '
            '- EEGLAB for .set files processing                                         '
            '- Before starting ensure that the EEG_TF is in the MATLAB path             '
            '                                                                           '
            'Basic functionality:                                                       '
            '- Type ''eeg_tf()'' in the MATLAB command line to launch the GUI             '
            'without any input data. Alternatively, it is also possible to pass input   ' 
            'arguments from the current MATLAB workspace by typing                      ' 
            '''eeg_tf(data, fs, time)'', where  data is 3D signal with dimentions         '
            '[channels, time, trials], fs is the sampling frequency in Hz (e.g. 128 Hz),'
            'time is start and end times in seconds (e.g. [-0.5, 1] sec), or full time  '
            'vector in seconds. If you pass the dataset as an argument, skip the next   '
            'step LOAD .SET DATA                                                        '
            '- Click LOAD .SET DATA to upload the existing dataset, you can choose      '
            'several datasets but ensure they have the same time range, conditions and  '
            'sampling frequency, otherwise launch analysis for each dataset separately. '
            'In the EEG data region you will see the information about the (first)      '
            'dataset uploaded: number of channels, number of time points, time range    '
            'and sampling rate. If the (ICA) weights for back projection are included in'
            'the EEGLAB dataset you will see the corresponding message in front of the  '
            'BSS/gBSS weights line                                                      '
            '- Click LOAD BSS/GBSS WEIGHTS to load the pre-saved weights, calculated not'
            ' in the framework of EEGLAB. This function is useful if the (g)BSS was done'
            'using other tools than EEGLAB. If there are no weights available in the    '
            'dataset and no weights uploaded, the analysis will be done in the electrode'
            ' space data.                                                               '
            '- Check ''Keep electrode space'' to avoid automatic projection data to the   '
            'source space. It is needed if there are weights in the dataset but you     '
            'do not want to use them.                                                   '
            '                                                                           '
            'Set parameters of the analysis                                             '
            '- Click CHOOSE EVENTS to choose the condition(s) of interest (if unset,    '
            'all conditions will be included)                                           '
            '- Choose COMPARE (2 conditions only) or MERGE (any number of conditions)   '
            'the data corresponding to the conditions                                   '
            '- Choose INDIVIDUAL or GROUP to perform analysis on each dataset or on the '
            'datasets grouped together (datasets have to be compatible, e.g. to have the'
            'same sampling rate, time range and conditions)                             '
            '- Set which channels to take for analysis (e.g. 1,2,3 or 1:3), each channel'
            'is treated independently and will be plotted in the separate figure        '
            '- Set frequency range of interest (e.g. 1:45)                              '
            '- Set time range of interest                                               '
            '                                                                           '
            'Set the parameters of the spectral decomposition (the default values in    '
            'this section are calculated automatically and can be kept for the fast     '
            'start :) )                                                                 '
            '- Choose the method of the spectra decomposition: Short-Time Fourier       '
            'Transform (uses the MATLAB function spectrogram(),                         ' 
            ' check https://www.mathworks.com/help/signal/ref/spectrogram.html for more '
            'info) or wavelets (based on the code from Mike X Cohen (2014) Fundamentals '
            'of Time-Frequency Analyses in Matlab/Octave. 1st ed, sinc(x) Press,        '
            'check https://www.sincxpress.com for more info)                            '
            '- Check if you want to transform data to dB (this function is useful to    '
            'compensate for the 1/f law, e.g. unify the resolution across frequencies)  '
            '- Set the baseline for dB transform (this applies to the wavelets only)    '
            '                                                                           '
            'Set advanced parameters of spectral decomposition                          '
            'Short-Time Fourier Transform                                               '
            '- Uncheck the ''Set default values'' option to be able to change the settings'
            '- Choose the window function: Hanning (default), Blackman or none. It is   '
            'recommended to use window function to avoid artifacts on the tf-maps       '
            '- Set the window length, note that the larger the window the better is the '
            'frequency resolution but worse is the time resolution, plus the signal is  '
            'more cut on the sides                                                      '
            '- Set the step with witch the window will be moving, smaller step increase '
            'the time resolution but may result in the longer computation time          '
            'Wavelet Transform                                                          '
            'Note: read the EEG_TF.PDF guide for detailed explanation of these settings '
            '- Uncheck the ''Set default values'' option to be able to change the settings'
            '- Change the type of correction of non-linearity: const (default) means    '
            'that wavelets with the same number of cycles will be applied at each       '
            'frequency, linear means that the the number of cycles will change linearly '
            'in the range indicated below, log leads to logarithmic change of the number'
            'of cycles in the range                                                     '
            '- Set the number of cycles as a single integer number or as a range        '
            '                                                                           '
            'Set parameters of plotting                                                 '
            '- Set at which time points you prefer to have landmarks (for example at the'
            'time of stimulus presentation, e.g. 0ms), can be left blank                '
            '- Set at which frequecnies you prefer to have landmarks (for example to    '
            'separate the alpha and beta activity, etc.), can be left blank             '
            '                                                                           '            
            '- Click PLOT SPECTROGRAM(S) to get the graphical results of the analysis   '
            '- Click SAVE IMAGES to automatically save images in .fig and .jpg formats  '
            'in the directory which you choose at demand (names are automatically       '
            'generated in the form ''EEG_TF_Image1.jpg'')                                 '
            '                                                                           '];
end

helpwin(helptext, helptitle);